name: Backend Skeleton
on:
  push:
    branches:
      - main
  pull_request: {}
  schedule:
    - cron:  '0 14 * * MON'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync
      # NOTE: there are nothing to test yet, unless we add some hooks, just check that it runs
      - name: Run tests on skeleton code
        run: uv run inv test.hooks
      - name: Build default project from skeleton and run tests
        run: |
          uv run cookiecutter --no-input --overwrite-if-exists --output-dir build .
          cd build/awesome
          cp ./api/.env.example ./api/.env
          cd api && uv lock && cd ..
          make api-test
